version: "3"
services:
  postgres:
    image: postgres:11.6
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "TZ=UTC"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  redis:
    image: redis:5.0.6
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    environment:
      - "TZ=UTC"
    volumes:
      - "redis-data:/data"
volumes:
  postgres-data: {}
  redis-data: {}
